package com.dev.ecomercesupplier.rest

class ApiUtils {
    companion object{
        const val DeviceType:String="2"
        const val Register:String="register"
        const val LOGIN:String = "login"
        const val ForgotPassword:String = "forgotPassword"
        const val VerifyAccount:String = "verifyAccount"
        const val ChangePassword:String = "changePassword"
        const val ResendOtp:String = "resendOtp"
        const val ResetPassword:String = "resetPassword"
        const val GetCountries:String = "getCountries"
        const val GetProfile:String = "getProfile"
        const val GetPackages:String = "getPackages"
        const val PackagePlanPayment:String = "packagePlanPayment"
        const val GetAccountTypes:String = "getAccountTypes"
        const val GetCategories:String = "getCategories"
        const val GetAttributesName:String = "getAttributesName"
        const val ChooseCategories:String = "chooseCategories"
        const val GetHomes:String = "getHomes"
        const val EditProfile:String = "editProfile"
        const val ContactUs:String = "contactUs"
        const val AddItem:String = "addItem"
        const val GetItem:String = "getItem"
        const val CouponAdd:String = "couponAdd"
        const val GetMyCoupons:String = "getMyCoupons"
        const val CouponDelete:String = "couponDelete"
        const val GetNotifications:String = "getNotifications"
        const val NotificationDelete:String = "notificationDelete"
        const val DeleteItem:String = "deleteItem"
        const val ReceiveOrders:String = "receiveOrders"
        const val AcceptReject:String = "acceptReject"
        const val EditBankDetail:String = "editBankDetail"
        const val GetTermsConditions:String = "getTermsConditions"
        const val GetPrivacyPolicy:String = "getPrivacyPolicy"
        const val GetAboutUs:String = "getAboutUs"
        const val GetFaq:String = "getFaq"
        const val UpdateCategory:String = "updateCategory"
        const val revenues:String = "revenues"
        var isCatClicked = 0
    }
}